import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

import manifest from "./manifest.json";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const VAULT_DIR =
  "/Users/lhak/Library/Mobile Documents/iCloud~md~obsidian/Documents/lhakZettel/";

const mode = process.argv[2];
const prod = mode === "production";
const deploy = mode === "deploy";

let outdir = "./";
if (deploy) {
  outdir = `${VAULT_DIR}.obsidian/plugins/${manifest.id}`;
} else if (!prod) {
  const vaultDir =
    process.env.REAL === "1" ? process.env.REAL_VAULT : process.env.TEST_VAULT;
  outdir = `${vaultDir}.obsidian/plugins/${manifest.id}`;
}

console.info(`\nSaving plugin to ${outdir}\n`);

const sveltePreprocessOptions = {
  scss: { silenceDeprecations: ["legacy-js-api"] },
  sass: { silenceDeprecations: ["legacy-js-api"] },
};

const buildOptions = {
  banner: { js: banner },
  minify: prod || deploy,
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "codemirror",
    "@codemirror/closebrackets",
    "@codemirror/commands",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  plugins: [
    esbuildSvelte({
      compilerOptions: {
        css: "injected",
        warningFilter: (w) =>
          ![
            "a11y_click_events_have_key_events",
            "a11y_no_static_element_interactions",
            "a11y_no_noninteractive_element_interactions",
            "element_invalid_self_closing_tag",
          ].includes(w.code),
      },
      preprocess: sveltePreprocess(sveltePreprocessOptions),
    }),
  ],
  define: { "import.meta.url": '"file:///plugin"' },
  logLevel: "info",
  logOverride: { "empty-import-meta": "silent" },
  sourcemap: prod || deploy ? false : "inline",
  treeShaking: true,
  outdir,
};

if (!prod && !deploy) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
} else {
  await esbuild.build(buildOptions).catch(() => process.exit(1));
}
